CREATE TABLE `users` (
  `id` INT(11) NOT NULL AUTO_INCREMENT,
  `fname` VARCHAR(255) NOT NULL,
  `lname` VARCHAR(255) NOT NULL,
  `nic` VARCHAR(15) NOT NULL,
  `uname` VARCHAR(255) NOT NULL,
  `bdate` DATE NOT NULL,
  `email` VARCHAR(40) NOT NULL,
  `address` VARCHAR(255) NOT NULL,
  `password` VARCHAR(15) NOT NULL,
  `gender` VARCHAR(10) NOT NULL,
  PRIMARY KEY (`id`)
) ENGINE=INNODB AUTO_INCREMENT=31 DEFAULT CHARSET=utf8mb4
